# Generated by Django 3.2.8 on 2022-05-30 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_menstrualcycle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menstrualcycle',
            name='Cycle_length',
            field=models.PositiveIntegerField(default=28),
        ),
        migrations.AddField(
            model_name='menstrualcycle',
            name='Period_length',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='parent',
            name='conscent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_body',
            field=models.FileField(default='', upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('audio_body', models.FileField(default='', upload_to='assets/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='index.post')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
