# Generated by Django 3.2.8 on 2022-06-17 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20220530_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(max_length=150)),
                ('audio', models.FileField(upload_to='MyFairy/assets/')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='audio_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='audio_body',
        ),
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.JSONField(default=str),
        ),
        migrations.AddField(
            model_name='parent',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.JSONField(default=str),
        ),
    ]
